
#include "runtime.h"

#include <stddef.h>

/* The 119 xboxkrnl ordinals this XBE imports. Names cross-checked against the
   Cxbx-Reloaded thunk table, which independently reproduces every mapping this
   project had already established from runtime evidence. */
static const struct {
    uint32_t ordinal;
    const char *name;
} kernel_imports[] = {
    {1u, "AvGetSavedDataAddress"},
    {2u, "AvSendTVEncoderOption"},
    {3u, "AvSetDisplayMode"},
    {4u, "AvSetSavedDataAddress"},
    {5u, "DbgBreakPoint"},
    {8u, "DbgPrint"},
    {14u, "ExAllocatePool"},
    {15u, "ExAllocatePoolWithTag"},
    {16u, "ExEventObjectType"},
    {17u, "ExFreePool"},
    {23u, "ExQueryPoolBlockSize"},
    {24u, "ExQueryNonVolatileSetting"},
    {40u, "HalDiskCachePartitionCount"},
    {44u, "HalGetInterruptVector"},
    {46u, "HalReadWritePCISpace"},
    {47u, "HalRegisterShutdownNotification"},
    {49u, "HalReturnToFirmware"},
    {65u, "IoCreateDevice"},
    {67u, "IoCreateSymbolicLink"},
    {69u, "IoDeleteSymbolicLink"},
    {74u, "IoInvalidDeviceRequest"},
    {81u, "IoStartNextPacket"},
    {83u, "IoStartPacket"},
    {87u, "IofCompleteRequest"},
    {95u, "KeBugCheck"},
    {97u, "KeCancelTimer"},
    {98u, "KeConnectInterrupt"},
    {99u, "KeDelayExecutionThread"},
    {100u, "ordinal 100 (unnamed in reference table)"},
    {107u, "KeInitializeDpc"},
    {109u, "KeInitializeInterrupt"},
    {113u, "KeInitializeTimerEx"},
    {119u, "KeInsertQueueDpc"},
    {124u, "KeQueryBasePriorityThread"},
    {128u, "KeQuerySystemTime"},
    {129u, "KeRaiseIrqlToDpcLevel"},
    {137u, "KeRemoveQueueDpc"},
    {139u, "KeRestoreFloatingPointState"},
    {142u, "KeSaveFloatingPointState"},
    {143u, "KeSetBasePriorityThread"},
    {144u, "KeSetDisableBoostThread"},
    {145u, "KeSetEvent"},
    {149u, "KeSetTimer"},
    {151u, "KeStallExecutionProcessor"},
    {153u, "KeSynchronizeExecution"},
    {156u, "KeTickCount"},
    {159u, "KeWaitForSingleObject"},
    {160u, "KfRaiseIrql"},
    {161u, "KfLowerIrql"},
    {164u, "LaunchDataPage"},
    {165u, "MmAllocateContiguousMemory"},
    {166u, "MmAllocateContiguousMemoryEx"},
    {167u, "MmAllocateSystemMemory"},
    {168u, "MmClaimGpuInstanceMemory"},
    {169u, "MmCreateKernelStack"},
    {170u, "MmDeleteKernelStack"},
    {171u, "MmFreeContiguousMemory"},
    {172u, "MmFreeSystemMemory"},
    {173u, "MmGetPhysicalAddress"},
    {175u, "MmLockUnlockBufferPages"},
    {176u, "MmLockUnlockPhysicalPage"},
    {178u, "MmPersistContiguousMemory"},
    {179u, "MmQueryAddressProtect"},
    {180u, "MmQueryAllocationSize"},
    {182u, "MmSetAddressProtect"},
    {184u, "NtAllocateVirtualMemory"},
    {187u, "NtClose"},
    {189u, "NtCreateEvent"},
    {190u, "NtCreateFile"},
    {196u, "NtDeviceIoControlFile"},
    {198u, "NtFlushBuffersFile"},
    {199u, "NtFreeVirtualMemory"},
    {200u, "NtFsControlFile"},
    {202u, "NtOpenFile"},
    {203u, "NtOpenSymbolicLinkObject"},
    {207u, "NtQueryDirectoryFile"},
    {211u, "NtQueryInformationFile"},
    {215u, "NtQuerySymbolicLinkObject"},
    {217u, "NtQueryVirtualMemory"},
    {218u, "NtQueryVolumeInformationFile"},
    {219u, "NtReadFile"},
    {224u, "NtResumeThread"},
    {225u, "NtSetEvent"},
    {226u, "NtSetInformationFile"},
    {231u, "NtSuspendThread"},
    {233u, "NtWaitForSingleObject"},
    {234u, "NtWaitForSingleObjectEx"},
    {236u, "NtWriteFile"},
    {238u, "NtYieldExecution"},
    {246u, "ObReferenceObjectByHandle"},
    {250u, "ObfDereferenceObject"},
    {255u, "PsCreateSystemThreadEx"},
    {258u, "PsTerminateSystemThread"},
    {259u, "PsThreadObjectType"},
    {269u, "RtlCompareMemoryUlong"},
    {277u, "RtlEnterCriticalSection"},
    {279u, "RtlEqualString"},
    {289u, "RtlInitAnsiString"},
    {291u, "RtlInitializeCriticalSection"},
    {294u, "RtlLeaveCriticalSection"},
    {301u, "RtlNtStatusToDosError"},
    {302u, "RtlRaiseException"},
    {304u, "RtlTimeFieldsToTime"},
    {305u, "RtlTimeToTimeFields"},
    {312u, "RtlUnwind"},
    {322u, "XboxHardwareInfo"},
    {323u, "XboxHDKey"},
    {324u, "XboxKrnlVersion"},
    {325u, "XboxSignatureKey"},
    {327u, "XeLoadSection"},
    {328u, "XeUnloadSection"},
    {335u, "XcSHAInit"},
    {336u, "XcSHAUpdate"},
    {337u, "XcSHAFinal"},
    {354u, "XboxAlternateSignatureKeys"},
    {356u, "HalBootSMCVideoMode"},
    {358u, "HalIsResetOrShutdownPending"},
    {359u, "IoMarkIrpMustComplete"},
    {360u, "HalInitiateShutdown"},
};

const char *recomp_kernel_ordinal_name(uint32_t ordinal)
{
    for (size_t i = 0; i < sizeof kernel_imports / sizeof kernel_imports[0];
         ++i) {
        if (kernel_imports[i].ordinal == ordinal) {
            return kernel_imports[i].name;
        }
    }
    return NULL;
}
